### ISSUE TITLE
ProviderTestCase3: unit tests has broken

### ISSUE THREAD

**Issue by ARNdroid** [ARNdroid/EasyTargetDiet#162]
<b>PROBLEM</b>
We are not sure about the exact moment (I now, shame on us!) but unit tests depending on ```ProviderTestCase3``` (package ```utils.sk.m217.testsutils```) are broken since migration to Android Studio 1.0.x.

The exception has this pattern:
```java
java.lang.SecurityException: The authority of the uri [our testing uri here] does not match the one of the contentProvider: null
at android.content.ContentProvider.validateIncomingUri(ContentProvider.java:1795)
at android.content.ContentProvider.access$000(ContentProvider.java:90)
at android.content.ContentProvider$Transport.query(ContentProvider.java:202)
at android.content.ContentResolver.query(ContentResolver.java:478)
at android.content.ContentResolver.query(ContentResolver.java:422)
...
```
The code below from ```ContentResolver``` (the Android class) is throwing the exception:
```java
    /** @hide */
    private void validateIncomingUri(Uri uri) throws SecurityException {
        String auth = uri.getAuthority();
        int userId = getUserIdFromAuthority(auth, UserHandle.USER_CURRENT);
        if (userId != UserHandle.USER_CURRENT && userId != mContext.getUserId()) {
            throw new SecurityException("trying to query a ContentProvider in user "
                    + mContext.getUserId() + " with a uri belonging to user " + userId);
        }
        if (!matchesOurAuthorities(getAuthorityWithoutUserId(auth))) {
            String message = "The authority of the uri " + uri + " does not match the one of the "
                    + "contentProvider: ";
            if (mAuthority != null) {
                message += mAuthority;
            } else {
                message += mAuthorities;
            }
            throw new SecurityException(message);
        }
    }
```
All classes inside ```utils.sk.m217.testsutils``` are created <a href="http://stackoverflow.com/questions/11482104/how-to-junit-test-contentresolver-notifychange">this way</a> and have internal Android code.

Seems like a security check was added on Android framework and the old code inside ```utils.sk.m217.testsutils``` are not creating dependencies complaint to this check.

<b>SOLUTION</b>

<u>Ideal</u>: Do the tests without using classes with Android internal code. Has Android now a way to test notify changes triggered by ```ContentProvider```?

<u>Not ideal</u>: Understand the solution inside ```utils.sk.m217.testsutils``` and make new classes using the updated Android internals.

<u>The ugly way</u>: Remove the broken tests.

**Comment by ARNdroid** [comment]
OK, we are not guilty: when upgrading to Android Studio 1.0.X the unit test ran without errors because we used Nexus 5 API 19 (KitKat). Some time later this device updated to API 21 (Lollipop) and the issue started.

Anyway, the problems is due to changes added on API 21. Because ```utils.sk.m217.testsutils``` uses old Android internals, it is not creating dependencies complaint to this changes.

**Comment by ARNdroid** [comment]
No one solution pointed above used. We will verify API level of device running the test methods and execute them only if the device API is compatible.

**Comment by ghost** [comment]
Hi, I stumbled upon this post. How are you creating the Content Providers? I had the same problem when calling MockContentResolverMethods since I was only instantiating my content providers this way:

```
MockContentResolver mockContentResolver = new MockContentResolver();
SampleContentProvider sampleContentProvider = new SampleContentProvider();
sampleContentProvider.attachInfo(context, null);

//SampleContentProvider.authority is content://<package name>.provider.SampleContentProvider/<simple name>
mockContentResolver.addProvider(SampleContentProvider.authority, sampleContentProvider)

```

This works when running the tests in devices with Android API < 21. This throws the same SecurityException when run in API >= 21 devices/emulators. The error was:

```
java.lang.SecurityException: The authority of the uri <test URI> does not match the one of the contentProvider: null
```

which means the contentProvider's authority was not set. We simply created a mock ProviderInfo with the actual authority URI that was passed in **mockContentResolver.addProvider**:

```
MockContentResolver mockContentResolver = new MockContentResolver();
SampleContentProvider sampleContentProvider = new SampleContentProvider();

//Added these lines
ProviderInfo providerInfo = new ProviderInfo();
providerInfo.authority = SampleContentProvider.authority;

sampleContentProvider.attachInfo(context, providerInfo); //attached providerInfo

//SampleContentProvider.authority is content://<package name>.provider.SampleContentProvider/<simple name>
mockContentResolver.addProvider(SampleContentProvider.authority, sampleContentProvider)
```

This is more than half a year late but I hope this helps anyone else who stumbles upon this thread.

**Comment by alceurneto** [comment]
@rcpvirtucio 
Hi!!
Thanks a lot!
I'll reopen this issue and make a new try using your advice.
